### ISSUE TITLE
"Group libvirtd does not exist"

### ISSUE THREAD

**Issue by magick93** [chouseknecht/minishift-up-role#2]
Im trying to run, but it fails, on Ubuntu 16.10, with the following:

```
PLAY [Install minishift] *******************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [chouseknecht.minishift-up-role : Install Docker machine driver] **********
included: /etc/ansible/roles/chouseknecht.minishift-up-role/tasks/Debian_driver.yml for localhost

TASK [chouseknecht.minishift-up-role : Downlodad the KVM driver] ***************
changed: [localhost]

TASK [chouseknecht.minishift-up-role : Install packages] ***********************
changed: [localhost] => (item=[u'libvirt-bin', u'qemu-kvm'])

TASK [chouseknecht.minishift-up-role : Get current user] ***********************
changed: [localhost]

TASK [chouseknecht.minishift-up-role : Add current uer to libvirtd group] ******
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Group libvirtd does not exist"}

NO MORE HOSTS LEFT *************************************************************
 [WARNING]: Could not create retry file 'minishift-up.retry'.         [Errno 2] No such file or directory: ''


PLAY RECAP *********************************************************************
localhost                  : ok=5    changed=3    unreachable=0    failed=1   
```

**Comment by johnreytanquinco** [comment]
OS: Ubuntu 17.04

I encountered the same error running the Playbook with everything set up and installed.
Anyone found fix for this?

**Comment by chouseknecht** [comment]
According to this [ubuntu help](https://help.ubuntu.com/lts/serverguide/libvirt.html), the correct group name is `libvirt`.

**Comment by domcam** [comment]
@chouseknecht  "After installing libvirt-bin, the user used to manage virtual machines will need to be added to the libvirtd group. Doing so will grant the user access to the advanced networking options."

Where do you see it referring to libvrt?

**Comment by domcam** [comment]
@chouseknecht Thanks Chris, just noticed the fine print. "In more recent releases (>= Yakkety) the group was renamed to libvirt. Upgraded systems get a new libvirt group with the same gid as the libvirtd group to match that."

Saved me from pulling more hair out :)

**Comment by jerrac** [comment]
FYI, I just ran into the opposite problem. I had to manually change `libvirt` to `libvirtd` before I could get it to work on Ubuntu 16.04... That was in the [Debian_driver.yml](./tasks/Debian_driver.yml) file.
